import numpy as np
# Module that generates the Hilbert curve
import hilbertGenerator as hilbGen
# Module that converts hilbert curve vertices into a graph
import graphTester as gt
# Module generating occupany map
import occupancyMapGen as occupyGen
# Module that converts the configuration space into CFree(obstacle-free points in Cspace) graph
import generateFreeSpace as getRand
# Module with functions that traverse the free space graph and search for hilbert curve vertices
import graphTraversal as traverse
# Module to evaluate whether or not the current order HCurve is a valid roadmap
import hilbertCurveEvaluator as hcEvaluator
import matplotlib.pyplot as plotter
import copy
# Module to start generating local solutions
import anchor 
# Order of the curve

def getNumCoordsFromString(set):
    keysIntSet = []
    # Since this is a dictionary we will first extract the keys
    keyStringSet = set.keys()
    #Iterating the string keys and converting them to integers
    for stringKey in keyStringSet:
        # Don't grab keys that were not found
        if set[stringKey] != True:
            continue
        currentStrX, currentStrY = stringKey.split(',')
        # Converting them to integers
        currentIntX = int(currentStrX)
        currentIntY =  int(currentStrY)
        keysIntSet.append([currentIntX,currentIntY])
    return keysIntSet

def plotHilbertPath(currentMap,hilbertCoords):
    # Plotting the map
    # HOLD ON from plotter
    plotter.ion
    plotter.imshow(currentMap,cmap='gray')
    # plotter.xticks([])
    # plotter.yticks([])
    # Removing the ticks
    #plotter.xticks([])
    #plotter.yticks([])
    # Converting hilbert vertices strings into integers
    # hilbertCoords = getNumCoordsFromString(pathNodes)
    # Grabbing our x and y coordinates
    xSet = []
    ySet = []
    for coord in hilbertCoords:
        currentX, currentY = coord
        xSet.append(currentX)
        ySet.append(currentY)
        pass
    # Plotting the lines generated by hilbert curves
    plotter.plot(xSet,ySet, linestyle='',linewidth=2,color='green',marker='o',markersize=3)
    plotter.draw()
    # Using plt.draw() instead of plt.show()
    print('HI!')
    #plotter.show()
    plotter.ioff

ORDERS = [2,3,4,5,6]
RESOLUTION = (100,100)
# TODO: 3. Create an occupancy map
generatedMaps = occupyGen.generateOccupancyMap(RESOLUTION) 
occupyGen.occupanyMapPlotter(generatedMaps)
# print(generatedMaps[1])
# VALID = None
# TODO: Delete these two counters
hitAppend = 0
hitValid = 0
generatedLabels = []
# RESOLUTION = (100,100)
VALID = None
freeSpace = getRand.generateFreeSpace(generatedMaps[6])
mapToIterate = len(generatedMaps)
# Anchor to solution(next part of project).
# Initialized the Anchor class and obtained straight line coordinates
"""GENERATING HILBERT CURVE"""
# Number of quadrants required for this order HC curve
ORDER = 4
QUADRANTS = 2 ** ORDER
# Total number of vertices
TOTAL_VERTICES = QUADRANTS*QUADRANTS
# PATH
PATH = [None] * TOTAL_VERTICES
# Hilbert Graphs
HILBERT_GRAPH = {}
# RESOLUTION
RESOLUTION = (100,100)
path = hilbGen.pathPlanner(PATH,ORDER,RESOLUTION) 
"""Randomizing the vertices"""
nodes = getRand.getRandomPoints(path)
"""Plotting the hilbert curve vertices"""
hilbGen.drawHilbert(RESOLUTION,path) 
hilbGen.drawHilbertRand(RESOLUTION,nodes)
hilbertGraph = gt.generateGraph(nodes,HILBERT_GRAPH)
# TODO: 5. Traverse the graph of Cfree and search for the Hilbert vertices in it
hilbertFound, visitedGraphs = traverse.getVertices(freeSpace,hilbertGraph)
myAnchor = anchor.Anchor({},freeSpace,(0,0),(100,100))
straighightLineMap = myAnchor.generateStraightLineCoordinates(100)
updatedMapper = myAnchor.getStraightLineVerticesInFreeSpace(straighightLineMap,freeSpace)
path = myAnchor.buildHilbertSolution(updatedMapper,(0,0),(100,100),hilbertFound,100,ORDER,1,RESOLUTION)
myAnchor.displayPath(path.head)
"""FROM THIS POINT ONWARD WE HAVE THE ORIGINAL IMAGE CLASSIFICATION CODE."""
for mapIdx in range(1,mapToIterate + 1):
    print(f'Going into map {mapIdx}. \n\n')
    print(f'Old map had valid HC of order {VALID} \n\n')
    VALID = None
    baseRemainingThresholdRatio = None
    # TODO: 4. Convert occupancy map into a graph of Cfree nodes
    copyCurrentMap = copy.deepcopy(generatedMaps[mapIdx])
    freeSpaceGraph = getRand.generateFreeSpace(generatedMaps[mapIdx])
    for ORDER in ORDERS:
        didBreak = False
        # Number of quadrants required for this order HC curve
        QUADRANTS = 2 ** ORDER
        # Total number of vertices
        TOTAL_VERTICES = QUADRANTS*QUADRANTS
        # PATH
        PATH = [None] * TOTAL_VERTICES
        # Hilbert Graphs
        HILBERT_GRAPH = {}
        # RESOLUTION
        RESOLUTION = (100,100)
        # TODO: 1. Create a Hilbert Curve
        path = hilbGen.pathPlanner(PATH,ORDER,RESOLUTION) 
        """Randomizing the vertices"""
        nodes = getRand.getRandomPoints(path)
        """Plotting the hilbert curve vertices"""
        hilbGen.drawHilbert(RESOLUTION,path) 
        hilbGen.drawHilbertRand(RESOLUTION,nodes)

        # TODO: 2. Generate a graph holding Hilbert curve vertices
        hilbertGraph = gt.generateGraph(nodes,HILBERT_GRAPH)
        # print(hilbertGraph)

        # TODO: 3. Create an occupancy map
        # generatedMaps = occupyGen.generateOccupancyMap(RESOLUTION) 
        # print(generatedMaps[1])
        # occupyGen.occupanyMapPlotter(generatedMaps)

        # TODO: 4. Convert occupancy map into a graph of Cfree nodes
        # freeSpaceGraph = getRand.generateFreeSpace(generatedMaps[1])
        # print(freeSpaceGraph)
        # TODO: 5. Traverse the graph of Cfree and search for the Hilbert vertices in it
        hilbertFound = traverse.getVertices(freeSpaceGraph,hilbertGraph)
        # TODO: 6. Evaluate whether this is a valid curve
        isValid,remainingThresholdPointsRatio = hcEvaluator.assesCurveValidity(hilbertFound[0])
        if isValid:
            hitValid+= 1
            print(f'hit valid: {hitValid}')
            VALID = ORDER
            baseRemainingThresholdRatio = 2
            print(f'Best Optimal path is along Hilbert Curve of order: {ORDER}')
            # Allow oversampling
            continue
        else:
            if ORDER == 3: # Setting our base threshold ration
                baseRemainingThresholdRatio = remainingThresholdPointsRatio
                VALID = ORDER
                continue
            elif remainingThresholdPointsRatio <= baseRemainingThresholdRatio + 1:# Evaluating the new ratio
                # Updating threshold in case we have a new best value/ to make our bounds tighter
                baseRemainingThresholdRatio = min(remainingThresholdPointsRatio,baseRemainingThresholdRatio)
                VALID = ORDER
                continue
            else:
                VALID = ORDER
                generatedLabels.append(VALID)
                hitAppend += 1
                print(f'hit append: {hitAppend}')
                print(f'Optimal path is along Hilbert Curve of order: {VALID}')
                # We will turn the valid order of hilbert curve into a numpy array and then append this array
                # labelsNpArray = np.append(labelsNpArray,np.array(VALID))
                didBreak = True
                break
   
    # TODO: Remove this line. Just added to grab points
    if didBreak:
        # TODO: Grab the hilberFound[0] to plot points
        # Current map
        currentMap = copyCurrentMap
        # Converting hilbert vertices strings into integers
        hilbertCoords = getNumCoordsFromString(hilbertFound[0])
        # We need to plot these xy values in map
        plotHilbertPath(currentMap,hilbertCoords)
        pass 
    
    # If all of the hilbert curves are iterated successfully
    # the algorithm will not break and we therefore have to store the label before 
    # progressing to the next occupancy map
    if not didBreak:# Handles edge case
        # TODO: Grab the hilberFound[0] to plot points
        generatedLabels.append(VALID)
        # Map we've just finished pathing
        currentMap = copyCurrentMap
        # Converting hilbert vertices strings into integers
        hilbertCoords = getNumCoordsFromString(hilbertFound[0])
        # We need to plot these xy values in map
        plotHilbertPath(currentMap,hilbertCoords)
        pass
